#!/bin/bash

# TODO: could the check be more error-prone? What if some mysql installations do not have ./mysql dir under the data dir?
if [ -d /var/lib/mysql/mysql ] 
then
  echo "MySQL seems to have already been initialized"
else
  mysql_install_db
  
  mysqld_safe &
  mysqladmin --silent --wait=30 ping || exit 1
  mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;"
  mysqladmin -u root password "$MYSQL_ROOT_PASSWORD";
  
  echo "MySQL data dir initialized and root password set from env var MYSQL_ROOT_PASSWORD"
fi